apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjpeg
  labels:
    app.kubernetes.io/name: mjpeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mjpeg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mjpeg
    spec:
      containers:
      - name: kceu
        image: squat/kubeconeu2019:arm64-latest
        imagePullPolicy: Always
        command:
        - /mjpeg
        args:
        - -d=/dev/video0
        - -l=:8080
        - -s=640x480
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: mjpeg
  labels:
    app.kubernetes.io/name: mjpeg
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: mjpeg
