apiVersion: apps/v1
kind: Deployment
metadata:
  name: servor
  labels:
    app.kubernetes.io/name: servor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: servor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: servor
    spec:
      containers:
      - name: servor
        imagePullPolicy: Always
        image: squat/servor:latest
        args:
        - --listen=0.0.0.0:8080
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: servor
  labels:
    app.kubernetes.io/name: servor
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: servor
